import './globals.css'
import type {Metadata} from 'next'
import {Open_Sans} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import {ThemeProvider} from "@/components/providers/theme-provider";
import {cn} from "@/lib/utils";

const font = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Meta Discord', description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
			<head>
				{/*<title>Meta Discords</title>*/}
				<link rel="icon" href="favicon-1.ico"/>
			</head>
			<body className={cn(font.className,"bg-orange-50 dark:bg-[#52524f]")}
			      style={{height: '100%'}}>
			<ThemeProvider
				attribute="class"
				defaultTheme="light"
				enableSystem={false}
				storageKey="discord-theme">
				{children}
			</ThemeProvider>
			</body>
			</html>
		</ClerkProvider>
	)
}
