import './globals.css'
import type {Metadata} from 'next'
import {Open_Sans} from 'next/font/google'
import {ClerkProvider} from '@clerk/nextjs'
import {ThemeProvider} from "@/components/providers/theme-provider";
import {cn} from "@/lib/utils";
import React from "react";
import ModalProvider from "@/components/providers/modal-provider";

const font = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Meta Discord', description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
			<head>
				{/*<title>Meta Discords</title>*/}
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>

			</head>
			<body className={cn(font.className,"bg-orange-50 dark:bg-[#52524f]")}
			      style={{height: '100%'}}>
			<ThemeProvider
				attribute="class"
				defaultTheme="dark"
				enableSystem={false}
				storageKey="discord-theme">
				<ModalProvider/>
				{children}
			</ThemeProvider>
			</body>
			</html>
		</ClerkProvider>
	)
}
